apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sapp
  template:
    metadata:
      labels:
        app: sapp
    spec:
      containers:
        - name: sapp
          image: swapna6555/s_repo:v1   # your Docker Hub image
          ports:
            - containerPort: 5000
